// PDF export service — generates a landscape A4 logbook PDF and presents
// the system print / share dialog via the `printing` package.
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'package:flight_path/shared/models/lesson.dart';
import 'package:flight_path/shared/models/app_user.dart';
import 'package:flight_path/shared/utils/exercise_helpers.dart';
import 'package:intl/intl.dart';

class PdfExportService {
  /// Generates a logbook PDF from the user's lesson list and opens the
  /// platform print / share dialog.
  static Future<void> exportLogbook({
    required List<Lesson> lessons,
    required AppUser user,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd/MM/yyyy');

    // Sort lessons by date ascending for a logbook.
    final sorted = List<Lesson>.from(lessons)
      ..sort((a, b) {
        final dateA = a.lessonDate ?? a.scheduledDate ?? a.createdAt;
        final dateB = b.lessonDate ?? b.scheduledDate ?? b.createdAt;
        return dateA.compareTo(dateB);
      });

    // Split into pages of ~15 entries.
    const entriesPerPage = 15;
    for (var pageStart = 0;
        pageStart < sorted.length;
        pageStart += entriesPerPage) {
      final pageEntries =
          sorted.skip(pageStart).take(entriesPerPage).toList();

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4.landscape,
          margin: const pw.EdgeInsets.all(20),
          build: (context) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              if (pageStart == 0) ...[
                pw.Text(
                  'Flight Path Training — Pilot Logbook',
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  '${user.displayName} | ${user.flightSchool}',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey700,
                  ),
                ),
                pw.SizedBox(height: 12),
              ],
              pw.TableHelper.fromTextArray(
                headerStyle: pw.TextStyle(
                  fontSize: 8,
                  fontWeight: pw.FontWeight.bold,
                ),
                cellStyle: const pw.TextStyle(fontSize: 7),
                cellAlignment: pw.Alignment.centerLeft,
                headerDecoration:
                    const pw.BoxDecoration(color: PdfColors.grey200),
                headers: [
                  'Date',
                  'Exercise',
                  'Type',
                  'Reg',
                  'From',
                  'To',
                  'Dual',
                  'PIC',
                  'Landings',
                  'Rating',
                  'Remarks',
                ],
                data: pageEntries.map((l) {
                  final date =
                      l.lessonDate ?? l.scheduledDate ?? l.createdAt;
                  final cId = compositeExerciseId(
                      l.exerciseId, l.subExercise);
                  return [
                    dateFormat.format(date),
                    exerciseDisplayName(cId),
                    _aircraftLabel(l.aircraftType),
                    l.aircraftRegistration,
                    l.departureAirfield,
                    l.arrivalAirfield,
                    l.dualTimeMinutes > 0
                        ? _minutesToHours(l.dualTimeMinutes)
                        : '',
                    l.picTimeMinutes > 0
                        ? _minutesToHours(l.picTimeMinutes)
                        : '',
                    '${l.landings}',
                    l.studentRating != null ? '${l.studentRating}/5' : '',
                    l.remarks,
                  ];
                }).toList(),
              ),
              pw.Spacer(),
              pw.Text(
                'Generated by Flight Path Training on ${dateFormat.format(DateTime.now())}',
                style: const pw.TextStyle(
                  fontSize: 7,
                  color: PdfColors.grey500,
                ),
              ),
            ],
          ),
        ),
      );
    }

    await Printing.layoutPdf(
      onLayout: (format) => pdf.save(),
      name:
          'Flight_Path_Logbook_${user.displayName.replaceAll(' ', '_')}',
    );
  }

  static String _minutesToHours(int minutes) {
    final h = minutes ~/ 60;
    final m = minutes % 60;
    if (h == 0) return '${m}m';
    if (m == 0) return '${h}h';
    return '${h}h ${m}m';
  }

  static String _aircraftLabel(String? type) {
    switch (type) {
      case 'cessna_152':
        return 'C152';
      case 'cessna_172':
        return 'C172';
      case 'pa28':
        return 'PA28';
      case 'pa28_181':
        return 'PA28-181';
      case 'pa38':
        return 'PA38';
      case 'da40':
        return 'DA40';
      case 'da20':
        return 'DA20';
      case 'robin_dr400':
        return 'DR400';
      case 'grob_g115':
        return 'G115';
      case 'tecnam_p2002':
        return 'P2002';
      default:
        return type ?? '';
    }
  }
}
