// PDF export service — generates a landscape A4 logbook PDF and presents
// the system print / share dialog via the `printing` package.
import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'package:flight_path/shared/models/lesson.dart';
import 'package:flight_path/shared/models/app_user.dart';
import 'package:flight_path/shared/utils/exercise_helpers.dart';
import 'package:intl/intl.dart';

class PdfExportService {
  /// Generates a logbook PDF from the user's lesson list and opens the
  /// platform print / share dialog.
  static Future<void> exportLogbook({
    required List<Lesson> lessons,
    required AppUser user,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd/MM/yyyy');

    // Sort lessons by date ascending for a logbook.
    final sorted = List<Lesson>.from(lessons)
      ..sort((a, b) {
        final dateA = a.lessonDate ?? a.scheduledDate ?? a.createdAt;
        final dateB = b.lessonDate ?? b.scheduledDate ?? b.createdAt;
        return dateA.compareTo(dateB);
      });

    // Split into pages of ~15 entries.
    const entriesPerPage = 15;
    for (var pageStart = 0;
        pageStart < sorted.length;
        pageStart += entriesPerPage) {
      final pageEntries =
          sorted.skip(pageStart).take(entriesPerPage).toList();

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4.landscape,
          margin: const pw.EdgeInsets.all(20),
          build: (context) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              if (pageStart == 0) ...[
                pw.Text(
                  'Flight Path Training — Pilot Logbook',
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  '${user.displayName} | ${user.flightSchool}',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey700,
                  ),
                ),
                pw.SizedBox(height: 12),
              ],
              pw.TableHelper.fromTextArray(
                headerStyle: pw.TextStyle(
                  fontSize: 8,
                  fontWeight: pw.FontWeight.bold,
                ),
                cellStyle: const pw.TextStyle(fontSize: 7),
                cellAlignment: pw.Alignment.centerLeft,
                headerDecoration:
                    const pw.BoxDecoration(color: PdfColors.grey200),
                headers: [
                  'Date',
                  'Exercise',
                  'Type',
                  'Reg',
                  'From',
                  'To',
                  'Dual',
                  'PIC',
                  'Landings',
                  'Rating',
                  'Remarks',
                ],
                data: pageEntries.map((l) {
                  final date =
                      l.lessonDate ?? l.scheduledDate ?? l.createdAt;
                  final cId = compositeExerciseId(
                      l.exerciseId, l.subExercise);
                  return [
                    dateFormat.format(date),
                    exerciseDisplayName(cId),
                    _aircraftLabel(l.aircraftType),
                    l.aircraftRegistration,
                    l.departureAirfield,
                    l.arrivalAirfield,
                    l.dualTimeMinutes > 0
                        ? _minutesToHours(l.dualTimeMinutes)
                        : '',
                    l.picTimeMinutes > 0
                        ? _minutesToHours(l.picTimeMinutes)
                        : '',
                    '${l.landings}',
                    l.studentRating != null ? '${l.studentRating}/5' : '',
                    l.remarks,
                  ];
                }).toList(),
              ),
              pw.Spacer(),
              pw.Text(
                'Generated by Flight Path Training on ${dateFormat.format(DateTime.now())}',
                style: const pw.TextStyle(
                  fontSize: 7,
                  color: PdfColors.grey500,
                ),
              ),
            ],
          ),
        ),
      );
    }

    await Printing.layoutPdf(
      onLayout: (format) => pdf.save(),
      name:
          'Flight_Path_Logbook_${user.displayName.replaceAll(' ', '_')}',
    );
  }

  /// Generates a single-lesson summary PDF and returns the file path.
  /// The caller is responsible for sharing the file (e.g. via share_plus).
  static Future<File> exportLessonSummaryPdf(Lesson lesson) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd/MM/yyyy');
    final date = lesson.lessonDate ?? lesson.scheduledDate ?? lesson.createdAt;
    final compositeId = compositeExerciseId(lesson.exerciseId, lesson.subExercise);
    final exerciseName = exerciseLongName(compositeId);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'Flight Path — Lesson Summary',
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              '$exerciseName — ${dateFormat.format(date)}',
              style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
            ),
            pw.SizedBox(height: 20),
            if (lesson.studentRating != null)
              pw.Text(
                'Self-rating: ${lesson.studentRating}/5',
                style: const pw.TextStyle(fontSize: 11),
              ),
            if (lesson.instructorRating != null)
              pw.Text(
                'Instructor rating: ${lesson.instructorRating}/5',
                style: const pw.TextStyle(fontSize: 11),
              ),
            if (lesson.lessonDuration > 0)
              pw.Text(
                'Duration: ${_minutesToHours(lesson.lessonDuration)}',
                style: const pw.TextStyle(fontSize: 11),
              ),
            pw.SizedBox(height: 16),
            if (lesson.instructorNotes.isNotEmpty) ...[
              pw.Text(
                'Instructor Comments',
                style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 4),
              pw.Text(lesson.instructorNotes,
                  style: const pw.TextStyle(fontSize: 11)),
              pw.SizedBox(height: 12),
            ],
            if (lesson.aiDebriefWell.isNotEmpty) ...[
              pw.Text(
                'What went well (AI)',
                style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 4),
              pw.Text(lesson.aiDebriefWell,
                  style: const pw.TextStyle(fontSize: 11)),
              pw.SizedBox(height: 12),
            ],
            if (lesson.aiDebriefImprove.isNotEmpty) ...[
              pw.Text(
                'What to improve (AI)',
                style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 4),
              pw.Text(lesson.aiDebriefImprove,
                  style: const pw.TextStyle(fontSize: 11)),
              pw.SizedBox(height: 12),
            ],
            if (lesson.aiDebriefFocus.isNotEmpty) ...[
              pw.Text(
                'Focus next lesson (AI)',
                style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 4),
              pw.Text(lesson.aiDebriefFocus,
                  style: const pw.TextStyle(fontSize: 11)),
              pw.SizedBox(height: 12),
            ],
            if (lesson.personalReflection.isNotEmpty) ...[
              pw.Text(
                'Personal Reflection',
                style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 4),
              pw.Text(lesson.personalReflection,
                  style: const pw.TextStyle(fontSize: 11)),
              pw.SizedBox(height: 12),
            ],
            pw.Spacer(),
            pw.Text(
              'Generated by Flight Path on ${dateFormat.format(DateTime.now())}',
              style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey500),
            ),
          ],
        ),
      ),
    );

    final bytes = await pdf.save();
    final dir = await getTemporaryDirectory();
    final safeName = exerciseName
        .replaceAll(RegExp(r'[^a-zA-Z0-9 _]'), '')
        .replaceAll(' ', '_');
    final file = File('${dir.path}/FlightPath_Lesson_$safeName.pdf');
    await file.writeAsBytes(bytes);
    return file;
  }

  static String _minutesToHours(int minutes) {
    final h = minutes ~/ 60;
    final m = minutes % 60;
    if (h == 0) return '${m}m';
    if (m == 0) return '${h}h';
    return '${h}h ${m}m';
  }

  static String _aircraftLabel(String? type) {
    switch (type) {
      case 'cessna_152':
        return 'C152';
      case 'cessna_172':
        return 'C172';
      case 'pa28':
        return 'PA28';
      case 'pa28_181':
        return 'PA28-181';
      case 'pa38':
        return 'PA38';
      case 'da40':
        return 'DA40';
      case 'da20':
        return 'DA20';
      case 'robin_dr400':
        return 'DR400';
      case 'grob_g115':
        return 'G115';
      case 'tecnam_p2002':
        return 'P2002';
      default:
        return type ?? '';
    }
  }
}
