// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMzAoWqQubu4k018n8Snl4KtdT_CuaS8Q',
    appId: '1:91239460645:android:2cfc53520e77366d2bf4cc',
    messagingSenderId: '91239460645',
    projectId: 'flight-path-fed56',
    storageBucket: 'flight-path-fed56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbeQq73SU-Wm04vlrCRe_S6OvHnvTQpN0',
    appId: '1:91239460645:ios:4ed7dc190ad183522bf4cc',
    messagingSenderId: '91239460645',
    projectId: 'flight-path-fed56',
    storageBucket: 'flight-path-fed56.firebasestorage.app',
    androidClientId: '91239460645-75e249ij97jc0v0es2b2t208m90tg22v.apps.googleusercontent.com',
    iosClientId: '91239460645-icufmfs2s081aje2pjg126ichtf8cpis.apps.googleusercontent.com',
    iosBundleId: 'uk.co.flightpath.flightPath',
  );
}
