// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWzzkqwYOqR0goFL52DpGKrP9xBDbXfGw',
    appId: '1:91239460645:web:d497ab935a62b6ed2bf4cc',
    messagingSenderId: '91239460645',
    projectId: 'flight-path-fed56',
    authDomain: 'flight-path-fed56.firebaseapp.com',
    storageBucket: 'flight-path-fed56.firebasestorage.app',
    measurementId: 'G-KBTDFFJWQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMzAoWqQubu4k018n8Snl4KtdT_CuaS8Q',
    appId: '1:91239460645:android:95d48b1c5bf130b12bf4cc',
    messagingSenderId: '91239460645',
    projectId: 'flight-path-fed56',
    storageBucket: 'flight-path-fed56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbeQq73SU-Wm04vlrCRe_S6OvHnvTQpN0',
    appId: '1:91239460645:ios:4ed7dc190ad183522bf4cc',
    messagingSenderId: '91239460645',
    projectId: 'flight-path-fed56',
    storageBucket: 'flight-path-fed56.firebasestorage.app',
    androidClientId: '91239460645-tniiajqlpm0q7r6jbikljpu8igj4vs1d.apps.googleusercontent.com',
    iosClientId: '91239460645-icufmfs2s081aje2pjg126ichtf8cpis.apps.googleusercontent.com',
    iosBundleId: 'uk.co.flightpath.flightPath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbeQq73SU-Wm04vlrCRe_S6OvHnvTQpN0',
    appId: '1:91239460645:ios:ee68e926136513eb2bf4cc',
    messagingSenderId: '91239460645',
    projectId: 'flight-path-fed56',
    storageBucket: 'flight-path-fed56.firebasestorage.app',
    androidClientId: '91239460645-tniiajqlpm0q7r6jbikljpu8igj4vs1d.apps.googleusercontent.com',
    iosClientId: '91239460645-hb75gthqlv2e43m5tcjlb6o0rbgs8mif.apps.googleusercontent.com',
    iosBundleId: 'com.flightpath.flightPath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWzzkqwYOqR0goFL52DpGKrP9xBDbXfGw',
    appId: '1:91239460645:web:2a5323caae19e6952bf4cc',
    messagingSenderId: '91239460645',
    projectId: 'flight-path-fed56',
    authDomain: 'flight-path-fed56.firebaseapp.com',
    storageBucket: 'flight-path-fed56.firebasestorage.app',
    measurementId: 'G-3J7E0L54MF',
  );
}
